### ISSUE TITLE
[FEATURE] Use prettier to format go template html

### ISSUE THREAD

**Issue by 713b76b7-2247-4bd5-98a7-014226363f9b** [HEIGE-PCloud/DoIt#1167]
### Describe the feature you want 描述你的功能需求

Need to manuallly format these janky html template during development is quite annoying.😭

> I can make a pr about this.

### Useful reference 有价值的参考

https://www.npmjs.com/package/prettier-plugin-go-template

**Comment by HEIGE-PCloud** [comment]
I added the support for it, but the go template syntax is quite obscure and it failed on some files

```
layouts/shortcodes/image.html
[error] layouts/shortcodes/image.html: Error: An error occured during printing. Found invalid node root.
[error]     at Object.print (/Users/pcloud/Code/DoIt/node_modules/prettier-plugin-go-template/lib/index.js:65:19)
[error]     at callPluginPrintFunction (file:///Users/pcloud/Code/DoIt/node_modules/prettier/index.mjs:22303:20)
[error]     at printAstToDoc (file:///Users/pcloud/Code/DoIt/node_modules/prettier/index.mjs:22258:22)
[error]     at async coreFormat (file:///Users/pcloud/Code/DoIt/node_modules/prettier/index.mjs:22611:14)
[error]     at async formatWithCursor (file:///Users/pcloud/Code/DoIt/node_modules/prettier/index.mjs:22809:14)
[error]     at async formatFiles (file:///Users/pcloud/Code/DoIt/node_modules/prettier/internal/cli.mjs:6673:18)
[error]     at async main (file:///Users/pcloud/Code/DoIt/node_modules/prettier/internal/cli.mjs:7081:5)
[error]     at async Module.run (file:///Users/pcloud/Code/DoIt/node_modules/prettier/internal/cli.mjs:7027:5)
```

It is what it is I guess...

**Comment by HEIGE-PCloud** [comment]
Turns out this is problematic, when Go template syntax and HTML are mixed together, changing the format might might breaks everything. I will revert this.
