### ISSUE TITLE
[BUG] Cloud not load the Waline comments. Waline 无法加载评论内容

### ISSUE THREAD

**Issue by WingsZeng** [HEIGE-PCloud/DoIt#487]
### Describe the bug 描述你遇到的错误

Cloud not load the Waline comments, showing loading. Waline 无法加载评论内容, 一直显示加载中
Error in console 控制台报错:
```
runtime-core.esm-bundler.js:6772 TypeError: Cannot read properties of null (reading 'insertBefore')
    at insert (Waline.min.js:1:66603)
    at A (Waline.min.js:1:46087)
    at m (Waline.min.js:1:43214)
    at N (Waline.min.js:1:51964)
    at $ (Waline.min.js:1:51232)
    at A (Waline.min.js:1:46245)
    at m (Waline.min.js:1:43214)
    at z (Waline.min.js:1:45640)
    at S (Waline.min.js:1:45033)
    at y (Waline.min.js:1:43685)
(anonymous) @ runtime-core.esm-bundler.js:6772
runtime-core.esm-bundler.js:6772 TypeError: Cannot read properties of null (reading 'insertBefore')
    at insert (Waline.min.js:1:66603)
    at x (Waline.min.js:1:44414)
    at y (Waline.min.js:1:43666)
    at m (Waline.min.js:1:43253)
    at R.fn (Waline.min.js:1:49865)
    at R.run (Waline.min.js:1:23409)
    at I (Waline.min.js:1:50157)
    at T (Waline.min.js:1:48412)
    at L (Waline.min.js:1:46358)
    at m (Waline.min.js:1:43278)
```

Related issue 相关 issue:
- walinejs/waline/issues/820

Refreshing did not work. 尝试刷新页面无效.
Destroying and re-instantiating Waline worked. 尝试在控制台中销毁并重新实例化 Waline, 评论内容成功加载.
Wrap the code with `setTimeout` worked. And `setTimeout(new Waline(), 0)` did work! 在 `setTimeout` 中实例化有效, 并且发现 `setTimeout(new Waline(), 0)` 居然也有效!
```js
if (window.config?.comment?.waline) {
  setTimeout(function() {new Waline(window.config.comment.waline)}, 0)
  // new Waline(window.config.comment.waline)
}
```
Although this is a solution, it looks strange. 虽然这样能够暂时解决, 但是感觉很奇怪.

### Expected behavior 期待的行为

Waline works well. Waline 评论正常显示.

### Screenshots 屏幕截图

![Screenshot from 2022-02-27 21-54-10](https://user-images.githubusercontent.com/50052878/155885274-2643feed-a98b-4062-87de-69c0507e7c25.png)

### Build Environment 构建环境

- OS: Ubuntu 20.04
- Hugo: v0.92.2+extended

### Preview Environment 预览环境

- OS: Ubuntu 20.04
- Brower: Chrome

### Additional Information 补充信息

Valine works well. Valine 正常.

**Comment by HEIGE-PCloud** [comment]
我发现在一些页面中一定会触发这个问题 如 https://hugodoit.pages.dev/theme-documentation-content/ 而在另一些页面中总不会触发这个错误 https://hugodoit.pages.dev/theme-documentation-basics/ 。

**Comment by HEIGE-PCloud** [comment]
进一步测试发现，只要页面中开启了 KaTeX

```
math:
  enable: true
```

似乎就会触发这个错误。
