### ISSUE TITLE
启动服务报错：fatal error: pipe failed

### ISSUE THREAD

**Issue by gxiaosong** [HEIGE-PCloud/DoIt#764]
### Describe the bug 描述你遇到的错误

运行： hugo server -D   报错如下：
Start building sites …
hugo v0.102.3-b76146b129d7caa52417f8e914fc5b9271bf56fc+extended darwin/amd64 BuildDate=2022-09-01T10:16:19Z VendorInfo=gohugoio
WARN 2022/10/28 21:17:14

Current environment is "development". The "comment system", "PWA", "CDN" and "fingerprint" will be disabled.
当前运行环境是 "development". "评论系统", "PWA", "CDN" 和 "fingerprint" 不会启用.

                   | EN | ZH-CN
-------------------+----+--------
  Pages            | 61 |     8
  Paginator pages  |  1 |     0
  Non-page files   |  0 |     0
  Static files     | 83 |    83
  Processed images |  0 |     0
  Aliases          | 14 |     0
  Sitemaps         |  2 |     1
  Cleaned          |  0 |     0

Built in 287 ms
Watching for changes in /Users/goez/git/blog/{archetypes,content,data,layouts,static,themes}
Watching for config changes in /Users/goez/git/blog/config.toml
fatal error: pipe failed

goroutine 1 [running]:
runtime.throw({0x5d5a6ab?, 0xc001e6e000?})
        /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0xc000f5d840 sp=0xc000f5d810 pc=0x40379bd
runtime.sigNoteSetup(0x4012d7c)
        /usr/local/go/src/runtime/os_darwin.go:101 +0xc5 fp=0xc000f5d868 sp=0xc000f5d840 pc=0x4034945
os/signal.signal_enable(0x2)
        /usr/local/go/src/runtime/sigqueue.go:205 +0x39 fp=0xc000f5d888 sp=0xc000f5d868 pc=0x4068099
os/signal.enableSignal(...)
        /usr/local/go/src/os/signal/signal_unix.go:49
os/signal.Notify.func1(0x5ac7320?)
        /usr/local/go/src/os/signal/signal.go:145 +0x73 fp=0xc000f5d8b0 sp=0xc000f5d888 pc=0x56f6c33
os/signal.Notify(0xc00333af60, {0xc000f5db58, 0x2, 0x0?})
        /usr/local/go/src/os/signal/signal.go:165 +0x1ff fp=0xc000f5d928 sp=0xc000f5d8b0 pc=0x56f6aff
github.com/gohugoio/hugo/commands.(*commandeer).serve(0xc00054e690, 0xc00053b0c0)
        /root/project/hugo/commands/server.go:573 +0x50c fp=0xc000f5db90 sp=0xc000f5d928 pc=0x572b8ac
github.com/gohugoio/hugo/commands.(*serverCmd).server(0xc00053b0c0, 0xc0009acc80, {0x0?, 0x0?, 0x0?})
        /root/project/hugo/commands/server.go:297 +0x3c8 fp=0xc000f5dcd8 sp=0xc000f5db90 pc=0x5727dc8
github.com/gohugoio/hugo/commands.(*commandsBuilder).newServerCmdSignaled.func1(0xc0009acc80?, {0xc0009b2850?, 0x1?, 0x1?})
        /root/project/hugo/commands/server.go:96 +0x36 fp=0xc000f5dd28 sp=0xc000f5dcd8 pc=0x5727896
github.com/spf13/cobra.(*Command).execute(0xc0009acc80, {0xc0009b2840, 0x1, 0x1})
        /root/project/gomodcache/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694 fp=0xc000f5de00 sp=0xc000f5dd28 pc=0x45aa014
github.com/spf13/cobra.(*Command).ExecuteC(0xc0009c4a00)
        /root/project/gomodcache/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd fp=0xc000f5deb8 sp=0xc000f5de00 pc=0x45aa69d
github.com/gohugoio/hugo/commands.Execute({0xc0000400d0, 0x2, 0x2})
        /root/project/hugo/commands/hugo.go:92 +0xbd fp=0xc000f5df38 sp=0xc000f5deb8 pc=0x5713d1d
main.main()
        /root/project/hugo/main.go:23 +0x56 fp=0xc000f5df80 sp=0xc000f5df38 pc=0x5731496
runtime.main()
        /usr/local/go/src/runtime/proc.go:250 +0x212 fp=0xc000f5dfe0 sp=0xc000f5df80 pc=0x403a1d2
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000f5dfe8 sp=0xc000f5dfe0 pc=0x406c361

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000078fb0 sp=0xc000078f90 pc=0x403a596
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.forcegchelper()
        /usr/local/go/src/runtime/proc.go:302 +0xad fp=0xc000078fe0 sp=0xc000078fb0 pc=0x403a42d
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000078fe8 sp=0xc000078fe0 pc=0x406c361
created by runtime.init.6
        /usr/local/go/src/runtime/proc.go:290 +0x25

goroutine 18 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000074790 sp=0xc000074770 pc=0x403a596
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
        /usr/local/go/src/runtime/mgcsweep.go:297 +0xd7 fp=0xc0000747c8 sp=0xc000074790 pc=0x4025817
runtime.gcenable.func1()
        /usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc0000747e0 sp=0xc0000747c8 pc=0x401a486
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000747e8 sp=0xc0000747e0 pc=0x406c361
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:178 +0x6b

goroutine 19 [GC scavenge wait]:
runtime.gopark(0xe22f37eff86f?, 0x11cdc94?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000074f70 sp=0xc000074f50 pc=0x403a596
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.(*scavengerState).park(0x742e7c0)
        /usr/local/go/src/runtime/mgcscavenge.go:389 +0x53 fp=0xc000074fa0 sp=0xc000074f70 pc=0x4023873
runtime.bgscavenge(0x0?)
        /usr/local/go/src/runtime/mgcscavenge.go:622 +0x65 fp=0xc000074fc8 sp=0xc000074fa0 pc=0x4023e65
runtime.gcenable.func2()
        /usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc000074fe0 sp=0xc000074fc8 pc=0x401a426
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000074fe8 sp=0xc000074fe0 pc=0x406c361
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:179 +0xaa

goroutine 3 [finalizer wait]:
runtime.gopark(0x742f4a0?, 0xc000102820?, 0x0?, 0x0?, 0xc000078770?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000078628 sp=0xc000078608 pc=0x403a596
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.runfinq()
        /usr/local/go/src/runtime/mfinal.go:180 +0x10f fp=0xc0000787e0 sp=0xc000078628 pc=0x401958f
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000787e8 sp=0xc0000787e0 pc=0x406c361
created by runtime.createfing
        /usr/local/go/src/runtime/mfinal.go:157 +0x45

goroutine 4 [GC worker (idle)]:
runtime.gopark(0xe22f46779bdf?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000079750 sp=0xc000079730 pc=0x403a596
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc0000797e0 sp=0xc000079750 pc=0x401c5d1
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000797e8 sp=0xc0000797e0 pc=0x406c361
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 34 [GC worker (idle)]:
runtime.gopark(0xe22f468da9d7?, 0x3?, 0x3c?, 0x57?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000508750 sp=0xc000508730 pc=0x403a596
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc0005087e0 sp=0xc000508750 pc=0x401c5d1
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0005087e8 sp=0xc0005087e0 pc=0x406c361
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 20 [GC worker (idle)]:
runtime.gopark(0xe22f468d98d3?, 0x3?, 0x9a?, 0x8a?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000075750 sp=0xc000075730 pc=0x403a596
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc0000757e0 sp=0xc000075750 pc=0x401c5d1
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000757e8 sp=0xc0000757e0 pc=0x406c361
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 35 [GC worker (idle)]:
runtime.gopark(0xe22f468da73c?, 0x1?, 0x37?, 0xbd?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000508f50 sp=0xc000508f30 pc=0x403a596
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc000508fe0 sp=0xc000508f50 pc=0x401c5d1
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000508fe8 sp=0xc000508fe0 pc=0x406c361
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 5 [GC worker (idle)]:
runtime.gopark(0xe22f468da033?, 0x3?, 0xf6?, 0xf?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000079f50 sp=0xc000079f30 pc=0x403a596
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc000079fe0 sp=0xc000079f50 pc=0x401c5d1
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000079fe8 sp=0xc000079fe0 pc=0x406c361
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 36 [GC worker (idle)]:
runtime.gopark(0xe22f468dadae?, 0x3?, 0x4?, 0xfe?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000509750 sp=0xc000509730 pc=0x403a596
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc0005097e0 sp=0xc000509750 pc=0x401c5d1
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0005097e8 sp=0xc0005097e0 pc=0x406c361
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 21 [GC worker (idle)]:
runtime.gopark(0xe22f468da08a?, 0x3?, 0xfc?, 0x3b?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00008bf50 sp=0xc00008bf30 pc=0x403a596
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc00008bfe0 sp=0xc00008bf50 pc=0x401c5d1
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00008bfe8 sp=0xc00008bfe0 pc=0x406c361
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 37 [GC worker (idle)]:
runtime.gopark(0xe22f468da6cc?, 0x3?, 0x35?, 0xd3?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000509f50 sp=0xc000509f30 pc=0x403a596
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1235 +0xf1 fp=0xc000509fe0 sp=0xc000509f50 pc=0x401c5d1
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000509fe8 sp=0xc000509fe0 pc=0x406c361
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1159 +0x25

goroutine 7 [select]:
runtime.gopark(0xc000076f88?, 0x3?, 0x10?, 0x4c?, 0xc000076f72?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000076df8 sp=0xc000076dd8 pc=0x403a596
runtime.selectgo(0xc000076f88, 0xc000076f6c, 0xc000124180?, 0x0, 0x0?, 0x1)
        /usr/local/go/src/runtime/select.go:328 +0x7bc fp=0xc000076f38 sp=0xc000076df8 pc=0x404a37c
go.opencensus.io/stats/view.(*worker).start(0xc000124180)
        /root/project/gomodcache/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0xad fp=0xc000076fc8 sp=0xc000076f38 pc=0x531e8ad
go.opencensus.io/stats/view.init.0.func1()
        /root/project/gomodcache/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x26 fp=0xc000076fe0 sp=0xc000076fc8 pc=0x531db26
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000076fe8 sp=0xc000076fe0 pc=0x406c361
created by go.opencensus.io/stats/view.init.0
        /root/project/gomodcache/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x8d

goroutine 348 [syscall]:
syscall.syscall6(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/sys_darwin.go:44 +0x99 fp=0xc003f1cc68 sp=0xc003f1cba8 pc=0x4068899
golang.org/x/sys/unix.kevent(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /root/project/gomodcache/golang.org/x/sys@v0.0.0-20220811171246-fbc7d0a398ab/unix/zsyscall_darwin_amd64.go:276 +0x52 fp=0xc003f1ccd0 sp=0xc003f1cc68 pc=0x41ebad2
golang.org/x/sys/unix.Kevent(0x0?, {0x0?, 0x0?, 0x0?}, {0xc003f1ce78?, 0x4007d65?, 0x0?}, 0x4014d05?)
        /root/project/gomodcache/golang.org/x/sys@v0.0.0-20220811171246-fbc7d0a398ab/unix/syscall_bsd.go:399 +0x3c fp=0xc003f1cd10 sp=0xc003f1ccd0 pc=0x41eb97c
github.com/fsnotify/fsnotify.read(0x0?, {0xc003f1ce78?, 0xc003f1ce08?, 0xa}, 0x5d26280?)
        /root/project/gomodcache/github.com/fsnotify/fsnotify@v1.5.4/kqueue.go:525 +0x3f fp=0xc003f1cd68 sp=0xc003f1cd10 pc=0x4dc2f1f
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc004663260)
        /root/project/gomodcache/github.com/fsnotify/fsnotify@v1.5.4/kqueue.go:288 +0xa5 fp=0xc003f1cfc8 sp=0xc003f1cd68 pc=0x4dc1f45
github.com/fsnotify/fsnotify.NewWatcher.func1()
        /root/project/gomodcache/github.com/fsnotify/fsnotify@v1.5.4/kqueue.go:63 +0x26 fp=0xc003f1cfe0 sp=0xc003f1cfc8 pc=0x4dc0ac6
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc003f1cfe8 sp=0xc003f1cfe0 pc=0x406c361
created by github.com/fsnotify/fsnotify.NewWatcher
        /root/project/gomodcache/github.com/fsnotify/fsnotify@v1.5.4/kqueue.go:63 +0x1c5

goroutine 349 [select]:
runtime.gopark(0xc003f1d788?, 0x3?, 0xf4?, 0x75?, 0xc003f1d73a?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc003f1d590 sp=0xc003f1d570 pc=0x403a596
runtime.selectgo(0xc003f1d788, 0xc003f1d734, 0x0?, 0x0, 0x0?, 0x1)
        /usr/local/go/src/runtime/select.go:328 +0x7bc fp=0xc003f1d6d0 sp=0xc003f1d590 pc=0x404a37c
github.com/gohugoio/hugo/watcher.(*Batcher).run(0xc004009b30)
        /root/project/hugo/watcher/batcher.go:67 +0x11a fp=0xc003f1d7c8 sp=0xc003f1d6d0 pc=0x570485a
github.com/gohugoio/hugo/watcher.New.func1()
        /root/project/hugo/watcher/batcher.go:56 +0x26 fp=0xc003f1d7e0 sp=0xc003f1d7c8 pc=0x5704706
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc003f1d7e8 sp=0xc003f1d7e0 pc=0x406c361
created by github.com/gohugoio/hugo/watcher.New
        /root/project/hugo/watcher/batcher.go:56 +0x1f6

goroutine 309 [select]:
runtime.gopark(0xc00007bfb0?, 0x2?, 0xd8?, 0xbd?, 0xc00007bf3c?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00007bda0 sp=0xc00007bd80 pc=0x403a596
runtime.selectgo(0xc00007bfb0, 0xc00007bf38, 0xc00007bf01?, 0x0, 0x0?, 0x1)
        /usr/local/go/src/runtime/select.go:328 +0x7bc fp=0xc00007bee0 sp=0xc00007bda0 pc=0x404a37c
github.com/gohugoio/hugo/commands.(*commandeer).newWatcher.func1()
        /root/project/hugo/commands/hugo.go:888 +0xf9 fp=0xc00007bfe0 sp=0xc00007bee0 pc=0x5719379
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00007bfe8 sp=0xc00007bfe0 pc=0x406c361
created by github.com/gohugoio/hugo/commands.(*commandeer).newWatcher
        /root/project/hugo/commands/hugo.go:886 +0x3ca

goroutine 310 [select]:
runtime.gopark(0xc001d56f28?, 0x3?, 0x40?, 0x4b?, 0xc001d56eca?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc001d56d40 sp=0xc001d56d20 pc=0x403a596
runtime.selectgo(0xc001d56f28, 0xc001d56ec4, 0x63ebce8?, 0x0, 0x63ebdc0?, 0x1)
        /usr/local/go/src/runtime/select.go:328 +0x7bc fp=0xc001d56e80 sp=0xc001d56d40 pc=0x404a37c
github.com/gohugoio/hugo/livereload.(*hub).run(0x742bd40)
        /root/project/hugo/livereload/hub.go:39 +0xec fp=0xc001d56fc8 sp=0xc001d56e80 pc=0x5701a2c
github.com/gohugoio/hugo/livereload.Initialize.func1()
        /root/project/hugo/livereload/livereload.go:107 +0x26 fp=0xc001d56fe0 sp=0xc001d56fc8 pc=0x5702026
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc001d56fe8 sp=0xc001d56fe0 pc=0x406c361
created by github.com/gohugoio/hugo/livereload.Initialize
        /root/project/hugo/livereload/livereload.go:107 +0x3f

### Build Environment 构建环境

hugo 版本：
hugo v0.102.3-b76146b129d7caa52417f8e914fc5b9271bf56fc+extended darwin/amd64 BuildDate=2022-09-01T10:16:19Z VendorInfo=gohugoio

尝试v0.103 v0.104 v0.105 都一样

系统版本：
macos Catalina

**Comment by gxiaosong** [comment]
解决了，不是hugo和主题问题
https://github.com/dillonzq/LoveIt/issues/750

**Comment by gxiaosong** [comment]
https://github.com/dillonzq/LoveIt/issues/750
